name: CI
on:
  push:
    branches:
      - main
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
      - name: Install dev dependencies
        run: npm install

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install submodules
        run: forge install

      - name: Run lint check
        run: npm run lint:check

      - name: Check gas snapshots
        run: forge snapshot --check

      - name: Run tests
        run: forge test

      - name: Run Slither
        uses: crytic/slither-action@main
        id: slither
        continue-on-error: true
        with:
          target: 'src/'
          sarif: results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}
